language: node_js
node_js:
- '10'
services:
- docker
before_install:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- docker login --username=_ --password=1319215a-58dd-4cff-b246-7f84f163c429 registry.heroku.com

script:
- docker build -t registry.heroku.com/test-180185/web .

deploy: 
  provider: script 
  script: 
    # push to dockerhub & heroku 
    docker push registry.heroku.com/test-180185/web
    heroku container: release web --app $ HEROKU_APP_NAME
   on: 
    branch: master