language: node_js
node_js:
- '10'
services:
- docker
before_install:
- docker login --username=_ --password=1319215a-58dd-4cff-b246-7f84f163c429 registry.heroku.com
- docker build -t registry.heroku.com/test-180185/web .
- docker push registry.heroku.com/test-180185/web
deploy:
  provider: heroku
  api_key:
    secure: dxQlrq9PytnykB6JLN4WvnB3GGEzhcDFLoCTU+ZVKdkAhyaM9f/AzmtFHMhhpw+f6m8XTNqrJr+FH7snfrE85Xncr6CLwp00UalItVQ4KYWNo3vs7r0jQWYkrlkFurZP0ZwPdC0rzr/2p45NwL7xZtOMKnCEybZW1GRk3oiDzuYhzn+rsHnY5VANnvvf5mVAewrd4dUbuPQWo34HwdPej+vGwz1QMOvsROPux0hNR0C1NFlDmEXhuG+qZHr9OeOH2pU8NWWIfKlgb0lecGNkXP2MeeYvpalr111p1Awpa/3/BT8+quRuOzLxDc1cTIgwlRpO4Lfi0BeY2HNvcVyP2msYhrqhx0o1HifDmnboA39JqVtHKEXNZq9gSb+EKpnAMDgfwgF2IOysEUrYtGqB1JVZmu8w1d+geHD+jp4LYUlyMe2iERr8vH6qAFN/NJLTG8lJhjYAgXFKIIK2LEYVhhxPnsQI6twLjM/ZViIRoJ9YV23LL9EPp1aeUVrhhdnh18fSCmKdJMC/CnHyc//zFncRX0OiVYzGKcJ9egRwjZ1TGfDZWSaaCl/Pndo4atdWelk0U7y0+zzzsXTNQbkIj02ff0XGqCoStiWyC98e8B3haM99q5ZL9uZB33FYXKwp7TBPtXuJ81kPBQChMQRxDgmPPvqbeNaR6v+8/G4MNSE=
  app: test-180185
  on:
    repo: ravish-goel/serve
