language: node_js
node_js:
- '10'
services:
- docker
before_install:
- docker login --username=_ --password=1319215a-58dd-4cff-b246-7f84f163c429 registry.heroku.com
- docker build -t registry.heroku.com/test-180185/web .
- docker push registry.heroku.com/test-180185/web
deploy:
  provider: heroku
  api_key:
    secure: SmTHAP3WZjmaWUdCsa0KHlwTXM5qa5wLqDVlmPQbzSnCB9mxGKFIC75vW9kAYYbbZZyhymuXApX+qJfbR1c+fSgaMeVOVBCEwY+vZx1gIjxVRFux1u7xcgVgISuNjylcRAc+VuRIcOQX0FzxNJNtbvEWilCNfkxgQIOHbF6VCbK26R9RMLHOQ57/b+PUSDmGIBCJKY6bK7CCFogZoPiVv0P4wGJMfJyOMIxAcNlPLd3EIj9JnL3EnRk5Hl0hAb0OaIyD/vwC7DUqB6IGMUjRwj2YS++DmG+vO4d0vy7WImk8j4lus6gYpY6zImHLBggqV2AXxONjlGrmMjjJjBkuNh5Gv1KdAMqZ0lX8EbO8Fz52tCKTS529UQECxdloIwELY7QQXDdaTbopT12N/A0g5Kekdtvenzm3J9cohcjNIljsB5E8GTEmt6Hm0n9biXjyiGH+9FqPeEreAL8GII2i2I1w+ZKLsh1EJzbGL0xHP6e7q1wrNe7q38F4UgmhdqF5tBTY9kYwJ6xSx834QKkvmkQNTlvZh/XuvWMoOF9PQAthoKhrzjnCX0nDEL9QPiZule4bNkzRcy+U2n4i8HpmD8sMqguMHy+13Am/gxoNvxqM68Ir3BiqfdtOq2zOzMWoKraK+58/E/xNb1k513EopDoybAiPxQZ+g1tj02nrb7E=
  app: test-180185
  on:
    repo: ravish-goel/serve
